name: GiGif
description: "A Flutter project of a GIF system."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # estado e UI
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0

  # armazenamento local e rede
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  http: ^1.2.0


  #  gerador de temas dinâmicos elegantes
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gifs/